import type { Language } from '../types';

export const translations: Record<Language, Record<string, string>> = {
  en: {
    title: "MazyLab",
    subtitle: "Instantly generate professional classified ads for your products.",
    upload_step_title: "Step 1: Upload Your Product Image(s) (1-3)",
    upload_image_label_1: "Image 1",
    upload_image_label_2: "Image 2",
    upload_image_label_3: "Image 3",
    upload_cta: "Click to upload",
    upload_subtext: "PNG, JPG, WEBP up to 10MB",
    upload_replace: "Click to replace image",
    composite_step_title: "Step 2: Generate Base Image",
    composite_prompt_label: "Image Description",
    composite_prompt_placeholder: "e.g., a professional photo of a red running shoe on a rock, or describe how to combine uploaded images",
    composite_cta: "Composite Images",
    generate_image_cta: "Generate Image",
    recomposite_cta: "Re-composite",
    clear_composite_cta: "Clear & Restart",
    download_composite_cta: "Download Composite",
    compositing_message: "Compositing your images...",
    generating_image_message: "Generating your image...",
    ad_type_step_title: "Step 3: Choose Ad Type",
    aspect_ratio_step_title: "Step 4: Choose Size & Resolution",
    image_ad: "Image Ad",
    video_ad: "Video Ad",
    category_step_title: "Step 5: Choose an Ad Category",
    template_step_title: "Step 6: Select an Ad Style",
    video_style_step_title: "Step 5: Select a Video Style",
    generating_ad: "Generating your ad...",
    generating_ad_subtext: "Gemini is thinking. This may take a moment.",
    generating_video: "Generating your video...",
    generating_video_subtext: "VEO is creating your masterpiece. This can take a few minutes.",
    ad_preview_title: "Your Ad is Ready!",
    close: "Close",
    error_title: "An Error Occurred",
    error_no_image: "Please upload an image before selecting a style.",
    error_no_composite: "Please create a composite image before selecting an ad type.",
    error_no_aspect_ratio: "Please select a size and resolution.",
    error_composite_need_two: "Please upload at least 2 images to composite.",
    error_prompt_empty: "Please enter a description to generate an image.",
    error_composite_failed: "Failed to composite images. Please try again.",
    error_generation_failed: "Failed to generate the ad. Please try again.",
    error_regeneration_failed: "Ad regeneration failed. Please try again.",
    ad_copy_prompt: "Ad Copy / Prompt:",
    switch_to_chinese: "中文",
    switch_to_english: "English",
    download_ad: "Download Image",
    download_video: "Download Video",
    share_ad: "Share",
    regenerate_ad: "Regenerate Ad",
    footer_text: "© 2024 MazyLab. Powered by Google Gemini.",
    // Auth
    auth_login_title: "Login to your account",
    auth_register_title: "Create a new account",
    auth_email: "Email Address",
    auth_password: "Password",
    auth_company: "Company (Optional)",
    auth_school: "School (Optional)",
    auth_industry: "Industry (Optional)",
    auth_phone: "Phone (Optional)",
    auth_login_cta: "Login",
    auth_logout_cta: "Logout",
    auth_register_cta: "Register",
    auth_no_account: "Don't have an account?",
    auth_has_account: "Already have an account?",
    auth_register_now: "Register now",
    auth_login_now: "Login now",
    auth_error_login_failed: "Login failed. Please check your email and password.",
    auth_error_register_failed: "Registration failed. This email may already be in use.",
    auth_error_empty: "Email and password cannot be empty.",
    auth_error_invalid_email: "Please enter a valid email address.",
    auth_error_password_length: "Password must be at least 6 characters long.",
    // Admin
    admin_panel_title: "Admin Panel",
    admin_back_to_app: "Back to App",
    admin_add_user: "Add New User",
    admin_edit_user: "Edit User",
    admin_error_email_exists: "A user with this email already exists.",
    admin_error_save: "Failed to save user data.",
    admin_error_delete_admin: "Cannot delete the admin account.",
    admin_confirm_delete: "Are you sure you want to delete this user?",
    admin_error_delete: "Failed to delete user.",
    admin_password_placeholder: "Leave blank to keep current password",
    admin_col_email: "Email",
    admin_col_company: "Company",
    admin_col_school: "School",
    admin_col_industry: "Industry",
    admin_col_phone: "Phone",
    admin_col_actions: "Actions",
    admin_edit: "Edit",
    admin_delete: "Delete",
    // General
    cancel: "Cancel",
    save: "Save",
  },
  zh: {
    title: "MazyLab 迷宮實驗室",
    subtitle: "即時為您的產品生成專業分類廣告。",
    upload_step_title: "第一步：上傳您的產品圖片 (1-3張)",
    upload_image_label_1: "圖片 1",
    upload_image_label_2: "圖片 2",
    upload_image_label_3: "圖片 3",
    upload_cta: "點擊上傳",
    upload_subtext: "支援 PNG, JPG, WEBP, 最大 10MB",
    upload_replace: "點擊替換圖片",
    composite_step_title: "第二步：生成基礎圖片",
    composite_prompt_label: "圖片描述",
    composite_prompt_placeholder: "例如：一張紅色跑鞋在岩石上的專業照片，或描述如何合成上傳的圖片",
    composite_cta: "合成圖片",
    generate_image_cta: "生成圖片",
    recomposite_cta: "重新合成",
    clear_composite_cta: "清除並重設",
    download_composite_cta: "下載合成圖",
    compositing_message: "正在合成您的圖片...",
    generating_image_message: "正在生成您的圖片...",
    ad_type_step_title: "第三步：選擇廣告類型",
    aspect_ratio_step_title: "第四步：選擇尺寸與解析度",
    image_ad: "圖片廣告",
    video_ad: "影片廣告",
    category_step_title: "第五步：選擇廣告類別",
    template_step_title: "第六步：選擇廣告風格",
    video_style_step_title: "第五步：選擇影片風格",
    generating_ad: "正在生成您的廣告...",
    generating_ad_subtext: "Gemini 正在思考，請稍候。",
    generating_video: "正在生成您的影片...",
    generating_video_subtext: "VEO 正在創作您的傑作。這可能需要幾分鐘時間。",
    ad_preview_title: "您的廣告已準備就緒！",
    close: "關閉",
    error_title: "發生錯誤",
    error_no_image: "請在選擇樣式前上傳圖片。",
    error_no_composite: "請在選擇廣告類型前建立合成圖。",
    error_no_aspect_ratio: "請選擇尺寸與解析度。",
    error_composite_need_two: "請至少上傳2張圖片進行合成。",
    error_prompt_empty: "請輸入描述以生成圖片。",
    error_composite_failed: "圖片合成失敗，請重試。",
    error_generation_failed: "廣告生成失敗，請重試。",
    error_regeneration_failed: "廣告重新生成失敗，請重試。",
    ad_copy_prompt: "廣告文案 / 提示詞:",
    switch_to_chinese: "中文",
    switch_to_english: "English",
    download_ad: "下載圖片",
    download_video: "下載影片",
    share_ad: "分享",
    regenerate_ad: "重新生成廣告",
    footer_text: "© 2024 MazyLab. 由 Google Gemini 驅動。",
    // Auth
    auth_login_title: "登入您的帳戶",
    auth_register_title: "建立新帳戶",
    auth_email: "電子郵件",
    auth_password: "密碼",
    auth_company: "公司 (可選)",
    auth_school: "學校 (可選)",
    auth_industry: "行業 (可選)",
    auth_phone: "電話 (可選)",
    auth_login_cta: "登入",
    auth_logout_cta: "登出",
    auth_register_cta: "註冊",
    auth_no_account: "還沒有帳戶？",
    auth_has_account: "已有帳戶？",
    auth_register_now: "立即註冊",
    auth_login_now: "立即登入",
    auth_error_login_failed: "登入失敗。請檢查您的電子郵件和密碼。",
    auth_error_register_failed: "註冊失敗。此電子郵件可能已被使用。",
    auth_error_empty: "電子郵件和密碼不能為空。",
    auth_error_invalid_email: "請輸入有效的電子郵件地址。",
    auth_error_password_length: "密碼長度至少為6個字元。",
    // Admin
    admin_panel_title: "管理員面板",
    admin_back_to_app: "返回應用程式",
    admin_add_user: "新增使用者",
    admin_edit_user: "編輯使用者",
    admin_error_email_exists: "此電子郵件已被註冊。",
    admin_error_save: "儲存使用者資料失敗。",
    admin_error_delete_admin: "無法刪除管理員帳戶。",
    admin_confirm_delete: "您確定要刪除此使用者嗎？",
    admin_error_delete: "刪除使用者失敗。",
    admin_password_placeholder: "留空以保留目前密碼",
    admin_col_email: "電子郵件",
    admin_col_company: "公司",
    admin_col_school: "學校",
    admin_col_industry: "行業",
    admin_col_phone: "電話",
    admin_col_actions: "操作",
    admin_edit: "編輯",
    admin_delete: "刪除",
    // General
    cancel: "取消",
    save: "儲存",
  }
};